apiVersion: v1
kind: Namespace
metadata:
  name: multiplexer-agent
---
apiVersion: v1
kind: Secret
metadata:
  name: multiplexer-agent-certs
  namespace: multiplexer-agent
  labels:
    app: multiplexer-agent
type: Opaque
stringData:
  agent.crt: |
    # paste agent certificate PEM here
  agent.key: |
    # paste agent private key PEM here
  server-ca.crt: |
    # paste server CA PEM here
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplexer-agent
  namespace: multiplexer-agent
  labels:
    app: multiplexer-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplexer-agent
  template:
    metadata:
      labels:
        app: multiplexer-agent
    spec:
      containers:
        - name: agent
          image: quixpublic.azurecr.io/agentmultiplexer:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_HOST
              value: "servermultiplexer.multiplexer.svc.cluster.local"
            - name: H2_PORT
              value: "8443"
            - name: AGENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: FORWARD_HOST
              value: "10.0.0.1"
            - name: FORWARD_PORT
              value: "6443"
            - name: TLS_CERT_FILE
              value: "/certs/agent.crt"
            - name: TLS_KEY_FILE
              value: "/certs/agent.key"
            - name: TLS_SERVER_CA_FILE
              value: "/certs/server-ca.crt"
          volumeMounts:
            - name: agent-certs
              mountPath: /certs
              readOnly: true
      volumes:
        - name: agent-certs
          secret:
            secretName: multiplexer-agent-certs
